#262 Refactor chips API
Orange-OpenSource/ods-ios pull request #548
Opened 2023-12-15 13:35 UTC by ludovic35

2023-12-19 15:13 UTC, pylapp requested changes
Quelques questions et commentaires assez rapides à traiter normalement

2023-12-19 15:13 UTC, pylapp commented on OrangeDesignSystemDemo/OrangeDesignSystemDemo/Screens/Components/Pages/Chips/FilterChipVariant.swift
> +class FilterChipVariantModel: ObservableObject {
_final_ à ajouter

2023-12-19 15:13 UTC, pylapp commented on OrangeDesignSystemDemo/OrangeDesignSystemDemo/Screens/Components/Pages/Chips/InputChipsVariant.swift
> +class InputChipVariantModel: ObservableObject {
_final_ à ajouter

2023-12-19 15:13 UTC, pylapp commented on OrangeDesignSystemDemo/OrangeDesignSystemDemo/Screens/Components/Pages/TextFields/CapitalizedTextInputsVariant.swift
> +                    // TODO, why                   .id(model.selectedCapitalizationType.description)
Pas compris le commentaire

2023-12-20 09:19 UTC, ludovic35 commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Components/BottomSheet/ODSBottomSheetExpanding.swift
>  // swiftlint:disbale comment_spacing multiline_parameters_brackets vertical_parameter_alignment
right, no need

2023-12-20 09:28 UTC, ludovic35 commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Components/Chips/Internal/Chip.swift
> +    let isSelected: Bool
tout a fait.

2023-12-20 10:37 UTC, pylapp commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Components/BottomSheet/ODSBottomSheetExpanding.swift
> +public enum ODSBottomSheetSize: Int, CaseIterable {
Mettre peut-être le _CaseIterable_ dans une extension interne à part

2023-12-20 10:38 UTC, pylapp commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Components/BottomSheet/ODSBottomSheetExpanding.swift
> +public enum ODSBottomSheetSize: Int, CaseIterable {
Retirer la commande _SwiftLint_ devenue inutile

2023-12-20 10:45 UTC, pylapp commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Components/Chips/Internal/Chip.swift
> +    var removeButton: some View {
On peut continuer d'avoir des _var_ tant que l'on n'a pas besoin de paramètres, parti pris poru deux solutions qui se valent.

2023-12-20 22:49 UTC, pylapp requested changes

2023-12-20 22:49 UTC, pylapp commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Components/Chips/Internal/Chip.swift
> +    private let action: () -> Void
Pour un peu plus de lisibilité je suggère dans cette _struct_ de définir un _typealias_ pour le type **() -> Void** de sorte à ce que l'on allège un peu le code.

Quelque chose dans ce goût :
```swift
typealias ChipAction = () -> Void
```

2023-12-20 22:49 UTC, pylapp commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Components/Chips/Internal/Chip.swift
> +                .padding(.all, 1)
Un padding de 1 seulement ?

2023-12-20 22:49 UTC, pylapp commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Components/Chips/Pickers/ODSChoiceChipPicker.swift
> +    public init(title: Text? = nil, chips: [ODSChoiceChip<Value>], selection: Binding<Value>, placement: ODSChipPickerPlacement = .carousel) {
Je me demande s'il n'y a pas une bonne pratique à appliquer côté Swift, à investiguer.
Sur les 4 paramètres on en a 3 qui ont des valeurs par défaut, et il me semble qu'ils devraient être à la fin.

2023-12-20 22:49 UTC, pylapp commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Components/Chips/Pickers/ODSChoiceChipPicker.swift
> +        return ODSChoiceChipView(chip: chip, selected: selection.wrappedValue == chip.value) {
Tu peux retirer le _return_ qui est superflu ici

2023-12-21 08:58 UTC, ludovic35 commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Components/Chips/Internal/Chip.swift
> +                .padding(.all, 1)
oui épaisseur du trait

2023-12-21 08:58 UTC, ludovic35 commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Components/Chips/Pickers/ODSChoiceChipPicker.swift
> +    public init(title: Text? = nil, chips: [ODSChoiceChip<Value>], selection: Binding<Value>, placement: ODSChipPickerPlacement = .carousel) {
oui mais à l'usage c'est beaucoup plus facile comme ça

2023-12-21 08:58 UTC, ludovic35 commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Components/Chips/Pickers/ODSChoiceChipPicker.swift
> +        return ODSChoiceChipView(chip: chip, selected: selection.wrappedValue == chip.value) {
yes

2023-12-21 08:58 UTC, ludovic35 commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Components/Chips/Internal/Chip.swift
> +    private let action: () -> Void
et removeAction ?
removeAction: (() -> Void)? = nil,

2023-12-21 08:58 UTC, ludovic35 commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Components/Chips/Internal/Chip.swift
> +                .padding(.all, 1)
je refactor pour la lecture

2023-12-21 09:03 UTC, pylapp commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Components/Chips/Internal/Chip.swift
> +    private let action: () -> Void
Vu _offline_ seul moi suit convaincu de la lisibilité du _typealias_

2023-12-21 09:04 UTC, pylapp approved these changes

2023-12-21 09:06 UTC, merged