[#542]Update guidelines typography names
Orange-OpenSource/ods-ios pull request #552
Opened 2023-12-18 13:05 UTC by ludovic35

2023-12-18 14:42 UTC, pylapp requested changes

2023-12-18 14:42 UTC, pylapp commented on OrangeDesignSystemDemo/OrangeDesignSystemDemo/Screens/Guidelines/Pages/Typography/TypographyPage.swift
>  extension ODSFontStyle {
Deux remarques sur ce point :
- on pourrait peut-être afficher dans la description l'équivalent iOS de la fonte choisie pour apporter plus de lisibilité
- le case `labelS` n'a pas la bonne valeur, elle 'na pas été migrée

On aurait alors quelque chose comme : 

```swift
extension ODSFontStyle {
    fileprivate var description: String {
        switch self {
        case .headlineL:
            return "Headline L (large title)"
        case .titleL:
            return "Title L (title 2)"
        case .titleM:
            return "Title M (title 3)"
        case .titleS:
            return "Title S (healdine)"
        case .headlineS:
            return "Headline S (title 1)"
        case .bodyLRegular:
            return "Body L Regular (body bold)"
        case .bodyLBold:
            return "Body L Bold (body bold)"
        case .bodyM:
            return "Body M (callout)"
        case .bodyS:
            return "Body S (subhead)"
        case .labelL:
            return "Label L (footnote)"
        case .labelMRegular:
            return "Label M Regular (caption 1 regulard)"
        case .labelMBold:
            return "Label M Bold (caption 1 bold)"
        case .labelS:
            return "Label S (caption 2)"
        }
    }
}
```

2023-12-18 15:12 UTC, ludovic35 commented on OrangeDesignSystemDemo/OrangeDesignSystemDemo/Screens/Guidelines/Pages/Typography/TypographyPage.swift
>  extension ODSFontStyle {
Ca veut die qu'il ne faut pas le faire ici, ça la valeur (la font choisie)  dépend du thème. Est-ce utile ?

2023-12-20 14:08 UTC, pylapp approved these changes

2023-12-20 14:09 UTC, merged