[#581] Bottom sheet states Voice Over vocalization
Orange-OpenSource/ods-ios pull request #687
Opened 2024-02-08 18:43 UTC by pylapp

# Issue

See #581

# Definition of Done

- [ ] Check any bottom sheets use in components and modules screens (demo app)

# For tests

_To be defined_

2024-02-12 16:50 UTC, ludovic35 requested changes

2024-02-12 16:50 UTC, ludovic35 commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Components/BottomSheet/Internal/ODSBottomSheetStandardModifier.swift
> +    /// - Parameter title: The title of the bottom sheet
missing parameters in documentation

2024-02-12 16:50 UTC, ludovic35 commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Components/BottomSheet/Internal/ODSBottomSheetStandardModifier.swift
> +    ///     - stateLabels:The accessibility labels to use for opened and closed states
missing space after :

2024-02-12 16:50 UTC, ludovic35 commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Components/BottomSheet/Internal/ODSBottomSheetStandardModifier.swift
> +    private func checkValues() {
rename to logValues and and #if DEBUG

2024-02-13 11:29 UTC, pylapp commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Components/BottomSheet/Internal/ODSBottomSheetStandardModifier.swift
> +    /// - Parameter title: The title of the bottom sheet
Où ça ?

2024-02-13 13:03 UTC, ludovic35 commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Components/BottomSheet/Internal/ODSBottomSheetStandardModifier.swift
> +    /// - Parameter title: The title of the bottom sheet
Mauvaise lecture, dsl

2024-02-13 13:06 UTC, merged