#684 Create module recirculation as a module
Orange-OpenSource/ods-ios pull request #705
Opened 2024-02-15 16:13 UTC by ludovic35

2024-02-16 16:39 UTC, pylapp requested changes
Quelques questions et remarques sur la forme et le fonctionnel à cause d'une régression notamment.

2024-02-16 16:39 UTC, pylapp commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Modules/About/Configuration/Items/Recirculation/ODSRecirculationItem.swift
>      ///    - priority: Priority to adjust the position of the item in the list.
La documentation du constructeur n'est pas à jour, il faut remplacer le premier paramètre _source_ par _dataSource_

2024-02-16 16:39 UTC, pylapp commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Modules/Recirculation/ODSRecirculationModel.swift
> +                let appsList = try await self.service.availableAppsList()
Il n'est pas utiliser de faire appel à `self` ici.
```swift
let appsList = try await service.availableAppsList()
loadingState = .loaded(flattenApps ? appsList.flattened() : appsList)
```

2024-02-16 16:39 UTC, pylapp commented on OrangeDesignSystemDemo/OrangeDesignSystemDemo/Screens/Modules/Recirculation/RecirculationModule.swift
> +                .disabled(!model.hasRemoteDateSource) // If no backend URL, force to use mocks
Le fonctionnel ici a été cassé. Normalement, si aucune URL n'est définie dans l'_Info.plist_ et donc exploitable, on désactive cet élément pour contraindre l'usage des _mocks_. Ceci dit ce choix d'implémentation est arbitraire, faute de specs. Le fait de ne plus avoir cette feature permet par effet de bord de tester le cas d'erreur où il n'y a aucune donnée.

Il faut donc choisir entre trois cas :
1. retirer la ligne 62 qui ne fonctionne plus en l'état, donc laisser le choix d'utiliser des bouchons ou non, peut importe si l'URL est définie
2. remettre en place le fonctionnel, à savoir désactiver ce premier _toggle_ si on n'a pas d'URL (définie par la chaîne de CI/CD au build pour ne pas avoir à versionner ou fuiter l'URL)
3. reprendre le 1er cas proposé, mais envisager d'afficher un message si par exemple l'URL n'est pas définie afin de ne pas surprendre l'utilisateur

2024-02-16 16:39 UTC, pylapp commented on OrangeDesignSystemDemo/OrangeDesignSystemDemo/Screens/Modules/Recirculation/RecirculationModuleModel.swift
> +        localDataSource = Self.localDataSource
Il faut renommer soit les propriétés locales soit les propriétés de classe car la lecture n'est pas efficace.

2024-02-16 16:39 UTC, pylapp commented on OrangeDesignSystemDemo/Podfile.lock
> +COCOAPODS: 1.15.1
Il faudrait cesser de rétrograder la version figée de CocoaPods , je te laisse vérifier sur ta machine mais cela fait plusieurs fois que je corrige derrière.

2024-02-19 09:31 UTC, ludovic35 commented on OrangeDesignSystemDemo/OrangeDesignSystemDemo/Screens/Modules/Recirculation/RecirculationModuleModel.swift
> +        localDataSource = Self.localDataSource
C'est à dire ?

2024-02-19 09:32 UTC, ludovic35 commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Modules/Recirculation/ODSRecirculationModel.swift
> +                let appsList = try await self.service.availableAppsList()
Yes

2024-02-19 09:32 UTC, ludovic35 commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Modules/About/Configuration/Items/Recirculation/ODSRecirculationItem.swift
>      ///    - priority: Priority to adjust the position of the item in the list.
Right

2024-02-19 09:37 UTC, ludovic35 commented on OrangeDesignSystemDemo/Podfile.lock
> +COCOAPODS: 1.15.1
oui bien soulant c'est histoires

2024-02-19 15:37 UTC, pylapp commented on OrangeDesignSystemDemo/OrangeDesignSystemDemo/Screens/Modules/Recirculation/RecirculationModule.swift
> +                .disabled(!model.hasRemoteDateSource) // If no backend URL, force to use mocks
Non reproduit.

2024-02-19 16:24 UTC, pylapp approved these changes

2024-02-19 16:25 UTC, pylapp commented on OrangeDesignSystemDemo/Podfile.lock
> +COCOAPODS: 1.15.1
C'est classique à gérer :)

2024-02-19 16:26 UTC, merged