#714 Update the demo configuration for recirculation module
Orange-OpenSource/ods-ios pull request #718
Opened 2024-02-21 13:21 UTC by ludovic35

2024-02-22 13:06 UTC, pylapp requested changes
Une expression à refactoriser et c'est tout.

2024-02-22 13:06 UTC, pylapp commented on OrangeDesignSystemDemo/OrangeDesignSystemDemo/Screens/Modules/Recirculation/RecirculationModuleModel.swift
> +        // If no remote url, force to use local data
Il y a une meilleure expression plus simple et dans le style booléen :
```swift
// If no remote url, force to use local data
useLocalDataSource = remoteDataSource == nil
```

2024-02-23 09:34 UTC, ludovic35 commented on OrangeDesignSystemDemo/OrangeDesignSystemDemo/Screens/Modules/Recirculation/RecirculationModuleModel.swift
> +        // If no remote url, force to use local data
Yes

2024-02-23 09:55 UTC, ludovic35 reviewed
Done

2024-02-23 10:09 UTC, pylapp approved these changes

2024-02-23 10:10 UTC, merged