[#801] Rename the Recirculation module to MoreApps
Orange-OpenSource/ods-ios pull request #806
Opened 2024-04-05 14:51 UTC by ludovic35

2024-04-08 13:37 UTC, pylapp requested changes
Il y a plusieurs chose à corriger : 

1. Le naming de tes structures de données n'est pas cohérent : il manque des mots et on perd du sens ; je t'ai fait des suggestions en commentaires
2. J'ai repéré trois warnings du linter ; il faudrait que tu regardes la configuration de SwiftLint chez toi ou que tu t'assurer de les corriger dans le code pour que les warnings soient corrigés (fichier **809 - review - SwiftLint**)
3. À un endroit dans le code tu changes un attribut au mauvais moment, ce qui déclenche un warning violet, à corriger (fichier **809 - review - synchro threads**)
4. Il y a d'ailleurs un problème de wording pour le menu About (fichier **809 - review - wording**)


<img width="733" alt="809 - review - SwiftLint" src="https://github.com/Orange-OpenSource/ods-ios/assets/7559007/1866ecf6-2148-49dd-bae9-1f8b5a80a116">

<img width="1130" alt="809 - review - synchro threads" src="https://github.com/Orange-OpenSource/ods-ios/assets/7559007/10d4391b-d148-4d54-92cd-5bd031c1228e">

![809 - review - wording](https://github.com/Orange-OpenSource/ods-ios/assets/7559007/6237da72-a8c5-418c-85ba-5ef1005936df)

2024-04-08 13:37 UTC, pylapp commented on OrangeDesignSystemDemo/OrangeDesignSystemDemo/Screens/Modules/MoreApps/MoreAppsModule.swift
>  // ===========================
Aligner la décoration, il y a trop de symboles "=" sur la lignes du dessus et du dessous

2024-04-08 13:37 UTC, pylapp commented on OrangeDesignSystemDemo/OrangeDesignSystemDemoTests/Modules/About/MoreApps/MoreAppsAppsPlusMapperTests.swift
> +        let lonelyApps: [MoreAppDetails] = appsPlusItemsMock.apps.map { appDTO in
Utiliser plutôt **[MoreAppsAppDetails]**

2024-04-08 13:37 UTC, pylapp commented on OrangeDesignSystemDemo/OrangeDesignSystemDemoTests/Modules/About/MoreApps/MoreAppsAppsPlusMapperTests.swift
> +        let sections: [MoreAppsListSection] = appsPlusItemsMock.sections.map { sectionDTO in
Utiliser plutôt **[MoreAppsAppsListSection**.

2024-04-08 13:37 UTC, pylapp commented on OrangeDesignSystemDemo/OrangeDesignSystemDemoTests/Modules/About/MoreApps/MoreAppsAppsPlusMapperTests.swift
> +    private func compare(businessObject: MoreAppDetails, dataTransferObject: AppsPlusAppDetailsDTO) {
Remplacer les occurrences de **MoreAppDetails** par **MoreAppsAppDetails**

2024-04-08 13:37 UTC, pylapp commented on OrangeDesignSystemDemo/OrangeDesignSystemDemoTests/Modules/About/MoreApps/MoreAppsBOTests.swift
> +        return MoreAppsList(sections: moreAppsSections, apps: moreAppsAppDetails)
Utiliser plutôt **MoreAppsAppsList**

2024-04-08 13:37 UTC, pylapp commented on OrangeDesignSystemDemo/fastlane/Fastfile
> +# URL for moreApps module to get feed from backend
Ortographier **MoreApps**

2024-04-08 14:19 UTC, ludovic35 commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Modules/EmptyState/ODSEmptyStateView.swift
> +
Non ,c'est comme ça partout sauf fabulation en trop

2024-04-09 08:32 UTC, pylapp requested changes
Il y a encore des soucis avec le renaming, et deux warnings non corrigés.
Il y a toujours me problème d'un wording cassé dans le menu _about_.

<img width="596" alt="801 - review 2 - missing wording" src="https://github.com/Orange-OpenSource/ods-ios/assets/7559007/f75a8924-380b-405c-8d89-b6d4a5d569e3">
<img width="987" alt="801 - review 2 - superfluous disable command" src="https://github.com/Orange-OpenSource/ods-ios/assets/7559007/ed4642a5-be69-4deb-a0c8-dafc4c6b27c6">
<img width="876" alt="801 - review 2 - trailing newline violation" src="https://github.com/Orange-OpenSource/ods-ios/assets/7559007/8b403082-f7f3-43a2-8627-3665bf84c77b">

2024-04-09 08:32 UTC, pylapp commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Modules/MoreApps/Domain/MoreAppsService.swift
> +    /// - Returns `MoreAppsList`: The parsed business objects
Ce n'est pas le bon type de donné qui est indiqué dans la documentation ; il faut utiliser à la place **MoreAppsAppsList**

2024-04-09 08:32 UTC, pylapp commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Modules/MoreApps/Domain/MoreAppsServiceBO.swift
> +// MARK: - MoreApps List
Il faut garder la cohérence entre les MARK de la minimap Xcode et les structures de données en dessous, ça donnerait quelque chose comme : 
```swift
// =====================
// MARK: More Apps Apps List
// =====================
```

2024-04-09 08:32 UTC, pylapp commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Modules/MoreApps/Domain/MoreAppsServiceBO.swift
>      /// - Returns MoreAppsList: Flattened version without changing `self`
Il faut indiquer *MoreAppsAppsList* en type de retour.

2024-04-09 08:32 UTC, pylapp commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Modules/MoreApps/Domain/MoreAppsServiceBO.swift
> +// MARK: - MoreApps List Section
Plutôt utiliser *MoreApps Apps List Section*

2024-04-09 08:32 UTC, pylapp commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Modules/MoreApps/ODSMoreAppsModel.swift
> +                if let modeAppsError = error as? ODSMoreAppsModel.Error {
Il y a une faute de saisie, _modeAppsError_ au lieu de _moreAppsError_.

2024-04-09 16:10 UTC, pylapp commented on OrangeDesignSystem/Sources/OrangeDesignSystem/Modules/MoreApps/Domain/MoreAppsServiceBO.swift
>      /// - Returns MoreAppsList: Flattened version without changing `self`
C'est de la documentation accessible aux dévleoppeurs et affichée notamment avec le _quick help_ Xcode. La base :)

2024-04-09 16:12 UTC, pylapp approved these changes

2024-04-09 16:14 UTC, merged